 ### TRUSTML CONFIG###
metrics:
    - AccuracySKL
    - PrecisionSKL:
        multiclass_average: "binary"
    - RecallSKL:
        multiclass_average: "binary"
    - F1SKL:
        multiclass_average: "binary"
    - ROCSKL:
        multiclass_average: "macro"
    - ExplanationsAccuracyTED:
        explainer_path: "demos/employees_retention/ted_explainer"
        explanations_path: "demos/employees_retention/ted_explanations"
assessment_method:
    WeightedAverage: # WEIGHTS FOR COMPUTING TRUST WITH THE WEIGHTED AVERAGED METHOD
        performance-0.5:
            AccuracySKL: 0.2
            PrecisionSKL: 0.2
            RecallSKL: 0.2
            F1SKL: 0.2
            ROCSKL: 0.2                
        explainability-0.5:                
            ExplanationsAccuracyTED: 1
    BayesianNetwork: # PARAMETERS FOR COMPUTING TRUST WITH A BAYESIAN NETWORK
        bn_path: "D:/DOGO4ML-PYTHON/demos/employees_retention/trust bn example-retention.dne"
        api_url: http://localhost:8080/api/ssi/assessment
        id_trust_node: Trust
        intervals_input_nodes:        
            - ROCSKL: [0.45, 0.8]
            - AccuracySKL: [0.45, 0.8]
            - PrecisionSKL: [0.45, 0.8]
            - RecallSKL: [0.45, 0.8]
            - F1SKL: [0.45, 0.8]
            - ExplanationsAccuracyTED: [0.45, 0.8]
    
    