 ### TRUSTML CONFIG###
metrics:
    - AccuracySKL
    - PrecisionSKL:
        multiclass_average: "binary"
    - RecallSKL:
        multiclass_average: "binary"
    - PPercentageSKL:
        protected_attributes: [statussex_A91,statussex_A92,statussex_A93,statussex_A94]
        positive_class: 1
    - EqualOpportunitySKL:
        protected_attributes: [statussex_A91,statussex_A92,statussex_A93,statussex_A94]
        positive_class: 1
    - FaithfulnessLIMESKL:
        explainer_path: "demos/german_credit/lime_explainer"
    - InvertedExpectedCalibrationSKL
    - InvertedBrierSKL
assessment_method:
    WeightedAverage:
            performance-0.4:
                AccuracySKL: 0.1
                PrecisionSKL: 0.2
                RecallSKL: 0.7
            uncertainty-0.2:                  
                InvertedBrierSKL: 0.5
                InvertedExpectedCalibrationSKL: 0.5
            explainability-0.1:                
                FaithfulnessLIMESKL: 1
            fairness-0.3:             
                PPercentageSKL: 0.5
                EqualOpportunitySKL: 0.5