 ### TRUST FOR RANDOM FOREST CLASSIFIERS ###
metrics: [AccuracySKL,PrecisionSKL,RecallSKL,PPercentageSKL,EqualOpportunitySKL,
    FaithfulnessLIMESKL,MonotonicityLIMESKL,InvertedExpectedCalibrationSKL,InvertedBrierSKL]
bn_parameters: # PARAMETERS FOR COMPUTING TRUST WITH A BAYESIAN NETWORK
    bn_path: "D:/Dropbox/PhD Marti Manzano/DOGO4ML/trust bn example.dne"
    api_url: http://localhost:8080/api/ssi/assessment
    id_si: Trust
    intervals_input_nodes:
        - RFAccuracy: [0.45, 0.8]
        - RFPrecision: [0.45, 0.8]
        - RFRecall: [0.45, 0.8]
        - RFF1: [0.45, 0.8]
        - RFROC: [0.45, 0.8]
        - RFPPercentage: [0.45, 0.8]
        - RFEqualOpportunity: [0.45, 0.8]
        - RFAverageBound: [0.45, 0.8]
        - RFVerifiedError: [0.45, 0.8]
        - RFMonotonicityLime: [0.45, 0.8]
        - RFFaithfulnessLime: [0.45, 0.8]
        - RFInvertedBrier: [0.45, 0.8]
        - RFInvertedExpectedCalibration: [0.45, 0.8]        
protected_attributes: # COLUMNS FOR FAIRNESS COMPUTATION
    - statussex_A91
    - statussex_A92
    - statussex_A93
    - statussex_A94
w.avg_parameters: # WEIGHTS FOR COMPUTING TRUST WITH THE WEIGHTED AVERAGED METHOD
    performance-0.4:      
        AccuracySKL: 0.1
        PrecisionSKL: 0.2
        RecallSKL: 0.7
    fairness-0.1:             
        PPercentageSKL: 0.5
        EqualOpportunitySKL: 0.5 
    explainability-0.2:                
        #MonotonicityLIMESKL: 1
        FaithfulnessLIMESKL: 1
    uncertainty-0.3:                  
        InvertedBrierSKL: 0.5
        InvertedExpectedCalibrationSKL: 0.5