 ### TRUST FOR RANDOM FOREST CLASSIFIERS ###
metrics: [ROCSKL,PPercentageSKL,EqualOpportunitySKL,
    VerifiedErrorSKLTree,AverageBoundSKLTree,FaithfulnessLIMESKL,MonotonicityLIMESKL,
    InvertedExpectedCalibrationSKL,InvertedBrierSKL]
bn_parameters: # PARAMETERS FOR COMPUTING TRUST WITH A BAYESIAN NETWORK
    bn_path: "D:/Dropbox/PhD Marti Manzano/DOGO4ML/trust bn example-red2.dne"
    api_url: http://localhost:8080/api/ssi/assessment
    id_si: Trust
    intervals_input_nodes:        
        - ROCSKL: [0.45, 0.8]
        - PPercentageSKL: [0.45, 0.8]
        - EqualOpportunitySKL: [0.45, 0.8]
        - AverageBoundSKLTree: [0.45, 0.8]
        - VerifiedErrorSKLTree: [0.45, 0.8]
        - MonotonicityLIMESKL: [0.45, 0.8]
        - FaithfulnessLIMESKL: [0.45, 0.8]
        - InvertedBrierSKL: [0.45, 0.8]
        - InvertedExpectedCalibrationSKL: [0.45, 0.8]        
protected_attributes: # COLUMNS FOR FAIRNESS COMPUTATION
    - statussex_A91
    - statussex_A92
    - statussex_A93
    - statussex_A94
w.avg_parameters: # WEIGHTS FOR COMPUTING TRUST WITH THE WEIGHTED AVERAGED METHOD
    performance-0.3:              
        ROCSKL: 1
    fairness-0.1:             
        PPercentageSKL: 0.5
        EqualOpportunitySKL: 0.5
    robustness-0.1:              
        AverageBoundSKLTree: 0.6
        VerifiedErrorSKLTree: 0.4            
    explainability-0.35:                
        MonotonicityLIMESKL: 0.4
        FaithfulnessLIMESKL: 0.6
    uncertainty-0.15:                  
        InvertedBrierSKL: 0.6
        InvertedExpectedCalibrationSKL: 0.4