w.avg_parameters: # WEIGHTS FOR COMPUTING TRUST WITH THE WEIGHTED AVERAGED METHOD
    performance:
        weight: 0.4
        perf_metrics:
            accuracy_weight: 0.1
            precision_weight: 0.2
            recall_weight: 0.7
            f1_weight: 0
    fairness:
        weight: 0.1
        fair_metrics:
            p-percentage_weight: 0.5
            equal_opportunity_weight: 0.5
    robustness:
        weight: 0
        rob_metrics:
            average_bound_weight: 0.6
            verified_error_inv_weight: 0.4            
    explainability:
        weight: 0.2
        expl_metrics_LIME:
            average_monotonicity_weight: 0.5
            average_faithfulness_weight: 0.5
        expl_metrics_TED:
            E_score_weight: 1
    uncertainty:
        weight: 0.3
        uncert_metrics:
            brier_inv_score_weight: 0.5
            expected_cal_inv_error_weight: 0.5