 ### TRUST FOR RANDOM FOREST CLASSIFIERS ###
bn_parameters: # PARAMETERS FOR COMPUTING TRUST WITH A BAYESIAN NETWORK
    bn_path: "D:/Dropbox/PhD Marti Manzano/DOGO4ML/trust bn example.dne"
    api_url: http://localhost:8080/api/ssi/assessment
    id_si: Trust
    intervals_input_nodes:
        - Accuracy: [0.45, 0.8]
        - Precision: [0.45, 0.8]
        - Recall: [0.45, 0.8]
        - F1: [0.45, 0.8]
        - P_Percentage: [0.45, 0.8]
        - Average_bound: [0.45, 0.8]
        - Verified_error_inv: [0.45, 0.8]
        - Average_monotonicity: [0.45, 0.8]
        - Average_faithfulness: [0.45, 0.8]
        - Brier_score_inv: [0.45, 0.8]
        - Expected_cal_error_inv: [0.45, 0.8]
        - Feedback: [0.45, 0.8]
feedback: # FEEDBACK (COMMON FOR BN AND W. AVG METHODS)
    weight: 0
    value: 1
protected_attributes: # COLUMNS FOR FAIRNESS COMPUTATION
    - SEX
w.avg_parameters: # WEIGHTS FOR COMPUTING TRUST WITH THE WEIGHTED AVERAGED METHOD
    performance:
        weight: 0.4
        perf_metrics:
            accuracy_weight: 0.1
            precision_weight: 0.2
            recall_weight: 0.7
            f1_weight: 0
    fairness:
        weight: 0.1
        fair_metrics:
            p-percentage_weight: 0.5
            equal_opportunity_weight: 0.5
    robustness:
        weight: 0
        rob_metrics:
            average_bound_weight: 0.6
            verified_error_inv_weight: 0.4            
    explainability:
        weight: 0.2
        expl_metrics_LIME:
            average_monotonicity_weight: 0.5
            average_faithfulness_weight: 0.5
        expl_metrics_TED:
            E_score_weight: 1
    uncertainty:
        weight: 0.3
        uncert_metrics:
            brier_inv_score_weight: 0.5
            expected_cal_inv_error_weight: 0.5